### ISSUE TITLE
not working in IE 11 because the dist files are not transpiled to ES5

### ISSUE THREAD

**Issue by axten** [mysticatea/abort-controller#15]
IE says: "Syntax Error class Abort Singal..."
I'm using it this way: `import 'abort-controller/polyfill';`

**Comment by mysticatea** [comment]
Thank you for this issue.

Yes, this is using ES2015 as similar to your `import` declaration. Please use transpiling in your bundler.

**Comment by axten** [comment]
hmm, a polyfill for old browsers that needs babel to work in old browsers is a bit strange...
why not adding a es5 version (like every other js lib in the wild)?

**Comment by mysticatea** [comment]
Because transpile is not zero cost. For example, it needs some glue code to reproduce classes for ES5. If each library has own glue code, those are redundant and increasing bundle size. On the other hand, app side transpiling can aggregate all glue code.

**Comment by axten** [comment]
agree, but imho this decision should be made by users, not by lib authors.
In fact, this polyfill is useless without babel (in contrast to all other polyfills I know).

**Comment by dptoot** [comment]
While I agree that the fact a polyfill needs to be transpiled is unique to this package,  i appreciate the functionality.   I am also running into a IE11 only transpilation issue but it is coming from `/event-target-shim/dist/event-target-shim.mjs`. Any assistance?  I have tried adding that to my include regex for babel-loader to no avail
