### ISSUE TITLE
umdOutro causes issues with webpack+babel

### ISSUE THREAD

**Issue by romainmenke** [mysticatea/abort-controller#19]
https://github.com/mysticatea/abort-controller/blob/a935d38e09eb95d6b633a8c42fcceec9969e7b05/rollup.config.js#L14

The `umdOutro` snippet causes issues when the polyfill is passed to webpack+babel.
We could not find a clear reason in your git history for adding this snippet.

We are also unsure if this is an issue with our config, webpack or babel.

Do you have any guidance or is there a change you can make to the snippet to resolve this issue?

Expected :

`"undefined" == typeof module && "undefined" == typeof define`

Actual :

`false && false`

Our config :

https://github.com/mrhenry/core-web/blob/test-suite/packages/core-web-tests/webpack.config.js

Our temporary patch :

https://github.com/mrhenry/core-web/blob/test-suite/packages/core-web-generator/generate.js#L102

**Comment by mysticatea** [comment]
I didn't intend that the UMD version is used with bundlers. It's provided for RequireJS or something like or for `<script>` tag way.

If you use this package with a bundler, please use bare import (e.g. `require("abort-controller")` / `import { AbortController } from "abort-controller"`) or importing polyfill file (e.g. `require("abort-controller/polyfill")` / `import "abort-controller/polyfill.mjs"`).
