### ISSUE TITLE
Uses es6 feature const that is not available in IE10.

### ISSUE THREAD

**Issue by AllNamesRTaken** [mysticatea/abort-controller#2]
I tried to uglify this for my app that supports IE10, but since you are using const, the uglify failes.
Why not transpile it to es5.

Also are there types for typescript?

**Comment by mysticatea** [comment]
Because Microsoft has dropped the support of IE10 since 2016/01/13.

**Comment by mysticatea** [comment]
This repo doesn't have `.d.ts` file. PR is Welcome.
