### ISSUE TITLE
TypeError: Class extends value undefined ... when importing

### ISSUE THREAD

**Issue by lsiden** [mysticatea/abort-controller#7]
When I attempt to run tests with jest, Node throws:

    TypeError: Class extends value undefined is not a constructor or null

    > 1 | import { AbortController } from "abort-controller"
      2 | import { ToastStyles } from "react-native-toaster"

This still works in the run-time app.

I tried mocking it out in the test with

    jest.mock("abort-controller")

but it doesn't make a difference.

**Comment by lsiden** [comment]
In order to resolve this, I had to add the following to any test file that indirectly imports abort-controller:

For example, in fetch.js:

    import AbortController from "abort-controller"

Then, in __test__/fetch.spec.js
    
```
	import { func1, func2, ... } from "../fetch"

    jest.mock("event-target-shim", () => ({
      EventTarget: () => "EventTarget",
      defineEventAttribute: () => "defineEventAttribute"
    }))
    jest.mock(
      "abort-controller",
      () =>
        class AbortController {
          abort() {}
        }
    )
```

Do you think this warrants a mod to the README file?  I can submit a PR if you are too busy.

**Comment by mysticatea** [comment]
Thank you for the investigation, and I'm sorry for my delay.

I'm not familiar with jest, but I feel odd if we have to know all indirect dependencies to use mocks because mocks should replace implementation and such indirect dependencies are the detail of implementation that should be replaced. Does jest really require the knowledge of implementation details to use mocks?

**Comment by lsiden** [comment]
Toru, I don't know how to write tests for logic that makes asynchronous requests (HTTP) without writing mocks.  I just didn't expect to have to write a mock for abort-controller and event-target-shim.

The problems appears to be that the node.js interpreter detects a circular reference when loading abort-controller.js and throws a run-time error. 

There is no problem when the browser loads abort-controller. By that time, all libraries have been transpiled into ES5 and bundled by Webpack.

You might want to consider using babel to transpile the .js files in both libraries into ES5 for the dist/ directory for maximum compatibility.

**Comment by mysticatea** [comment]
> Toru, I don't know how to write tests for logic that makes asynchronous requests (HTTP) without writing mocks. I just didn't expect to have to write a mock for abort-controller and event-target-shim.

I don't say "don't use mocks", but I suspect that jest's mock system has a critical defect that messes library to replace indirect dependencies with undefined.

> The problems appears to be that the node.js interpreter detects a circular reference when loading abort-controller.js and throws a run-time error.

No. Any circular references don't exist in this library. I think that Jest hacks and overwrites Node.js's module loading behavior and it messes `require("event-target-shim")` of this library. Mock libraries need such hacks. But sane mocks would not replace internal dependencies with undefined silently.

> You might want to consider using babel to transpile the .js files in both libraries into ES5 for the dist/ directory for maximum compatibility.

I don't think that I want to inflate the source code as unnecessary.

**Comment by lsiden** [comment]
Okay,  thanks.
