### ISSUE TITLE
fails to minify

### ISSUE THREAD

**Issue by CWSites** [mysticatea/abort-controller#9]
I added your package to my React app and now I'm unable to compile my production build because of the following error.

```
Failed to minify the code from this file: 

 	./node_modules/abort-controller/dist/abort-controller.mjs:20 
```

**Comment by czebe** [comment]
We're experiencing the same issue with older UglifyJS.

**Comment by mysticatea** [comment]
Closing as this is not a problem in this repo. Please use a minification tool that supports ES2015.

**Comment by CWSites** [comment]
@mysticatea, create-react-app doesn't support ES2015??

**Comment by divsbhalala** [comment]
I am having the same issue create-react-app

**Comment by jwerardi** [comment]
has anyone found a fix for this?

**Comment by CC802** [comment]
我也遇到这个问题暂时找不到解决方案
